language: node_js
node_js:
  - "stable"
before_script:
  - npm install -g gulp
script:
  - gulp
  - gulp images
  - ls ./public/
deploy:
  skip_cleanup: true    
  provider: surge
  project: ./public/