language: node_js
node_js:
  - "stable"
before_script:
  - npm install -g gulp
  - npm install --global surge
script:
  - gulp images
  - gulp

deploy:
  provider: surge
  project: ./public/
  domain: bolt.surge.sh